### ISSUE TITLE
Setting up the Kanbab board

### ISSUE THREAD

**Issue by fherrerao** [ixboy/Space-Travelers-Hub#65]
# Hi There 💯 
## In this issue:

- We share the link to the project: [Space Travelers Hub](https://github.com/ixboy/Space-Travelers-Hub/projects/2)
- We are two people in the project.

Please, let us know if we need to make changes.

**Comment by Meltrust** [comment]
Hi team,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)





Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fherrerao** [comment]
Thanks, @Meltrust for your review 🥇 .
